### ISSUE TITLE
endianness is not working in "value" field

### ISSUE THREAD

**Issue by IlyaER** [ustropo/uttlv#17]
I've set endianness to be little-endian, however the **value** part of TLV is not represented in little-endian way.

```
from uttlv import TLV

t = TLV(tag_size=2, len_size=4, endian="little")
t[1] = 128
print(t.to_byte_array())
```
Expected output:
`b'\x01\x00\x04\x00\x00\x00\x80\x00\x00\x00'`

Current output:
`b'\x01\x00\x04\x00\x00\x00\x00\x00\x00\x80'`

**Comment by ustropo** [comment]
Fixed with PR #19
