### ISSUE TITLE
Supporting nested tag maps

### ISSUE THREAD

**Issue by davidlenfesty** [ustropo/uttlv#4]
I'm using this library with nested TLV structures, and the current tag map implementation is not suitable for the use case. Even if you only set a tag map for the top level structure, it modifies how tags are parsed in the sub-structures.

I've subclassed the existing implementation to hack in a fix, I don't hate the solution and I think it would be reasonable to implement close to as is. (I basically just swap out the class-global TLV for a local attribute when we want to override it - note that this implementation *doesn't* apply new tag maps to any existing TLV objects, as it would in the current implementation)

```python
class MyTLV(TLV):
    """Override several bits of the original to provide *local* tag maps."""
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._tag_map = TLV.tag_map

    # XXX if we can instead swap out this attribute, then we can properly emulate existing behaviour
    #     self.tag_map = foo doesn't work, have to dig *slightly* deeper into python
    @property
    def tag_map(self):
        return self._tag_map
       
    def set_local_tag_map(self, map):
        """Swaps out tag map property so we can have local changes"""
        self._tag_map = map

    def __getkey__(self, key):
        '''Get real tag from a given string'''
        if isinstance(key, int):
            return key
        if isinstance(key, str):
            for k, v in self.tag_map.items():
                name = v.get(TLV.Config.Name)
                if name and name == key:
                    return k
            raise AttributeError(f'Key {key} not found')
        # Invalid key type
        raise KeyError(f'Invalid key {str(key)}')

    def parse_array(self, data):
        '''Parse a byte array into a TLV object'''
        if isinstance(data, list):
            data = bytes(data)
        elif not isinstance(data, bytes):
            raise TypeError('Data must be bytes type.')
        # Check size
        min_len_size = self.len_size or 1
        min_size = min_len_size + self.tag_size
        if len(data) < min_size:
            raise AttributeError(f'Data must be at least {min_size} bytes long')
        # Start parsing
        aux = data
        while len(aux) > min_size:
            # Tag value
            t = int.from_bytes(aux[:self.tag_size], byteorder=self.endian)
            # Len value
            aux = aux[self.tag_size:]
            len_size = self.len_size or self.decode_len_size(aux)
            offset = 0 if len_size == 1 else 1
            l = int.from_bytes(aux[offset:len_size], byteorder=self.endian)
            # Value
            aux = aux[len_size:]
            v = aux[:l]
            # Next value
            aux = aux[l:]
            # Check if tag has any parser
            tg_cfg = self.tag_map.get(t)
            if tg_cfg is not None:
                tg_type = tg_cfg.get(TLV.Config.Type)
                if tg_type is not None:
                    frm = uttlv.tlv.ALLOWED_TYPES.get(tg_type)
                    if frm is not None:
                        v = frm().parse(v, TLV(self.indent, self.tag_size, self.len_size, self.endian))
            # Set value
            self.__setitem__(t, v)
        # Done parsing
        return True
```

This doesn't completely resolve the issue, as parsing nested TLV structures requires some manual intervention. (because the DefaultEncoder doesn't apply any tag maps as it stands). I didn't implement this but an easy way to implement it IMO would be to allow a fourth type in the tag map dictionary, a dictionary that simply defines another tag map. This way the new TLV object can be created, initialized with the correct tag map, and then parse the incoming data.

Happy to create a PR, just felt it would be a bit presumptious given how many possible solutions there are and this feature set may have been explicitly avoided.

**Comment by ustropo** [comment]
In my original use case for this, I didn't need to use nested TLV structures, but I know some protocols that use them, so I think this could be helpful. 

Please, if you could, create a PR if your modifications, will be happy to review and add them. 

P.S.: please, add some unit tests and update the doc on how to use them. Thank you!
